-- return {
--   "nvim-tree/nvim-tree.lua",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   config = function()
--     local nvimtree = require "nvim-tree"
--
--     -- recommended settings from nvim-tree documentation
--     vim.g.loaded_netrw = 1
--     vim.g.loaded_netrwPlugin = 1
--     -- change color for arrows in tree to light blue
--     vim.cmd [[ highlight NvimTreeFolderArrowClosed guifg=#3FC5FF ]]
--     vim.cmd [[ highlight NvimTreeFolderArrowOpen guifg=#3FC5FF ]]
--
--     -- configure nvim-tree
--     nvimtree.setup {
--       view = {
--         width = 30,
--         relativenumber = true,
--       },
--       -- change folder arrow icons
--       renderer = {
--         indent_markers = {
--           enable = true,
--         },
--         icons = {
--           webdev_colors = true,
--           git_placement = "before",
--           modified_placement = "after",
--           padding = " ",
--           symlink_arrow = " ➛ ",
--           show = {
--             file = true,
--             folder = true,
--             folder_arrow = true,
--             git = true,
--             modified = true,
--           },
--
--           glyphs = {
--             default = "",
--             symlink = "",
--             bookmark = "",
--             modified = "●",
--             folder = {
--               arrow_closed = "",
--               arrow_open = "",
--               default = "",
--               open = "",
--               empty = "",
--               empty_open = "",
--               symlink = "",
--               symlink_open = "",
--             },
--
--             git = {
--               unstaged = "✗",
--               staged = "✓",
--               unmerged = "",
--               renamed = "➜",
--               untracked = "★",
--               deleted = "",
--               ignored = "◌",
--             },
--           },
--         }, -- end of icons rendering
--       },
--       -- disable window_picker for
--       -- explorer to work well with
--       -- window splits
--       actions = {
--         open_file = {
--           window_picker = {
--             enable = false,
--           },
--         },
--       },
--       filters = {
--         custom = { ".DS_Store" },
--         dotfiles = true,
--       },
--       git = {
--         ignore = false,
--       },
--       ui = {
--         confirm = {
--           remove = true,
--           trash = true,
--         },
--       },
--     }
--     vim.cmd "highlight NvimTreeNormalNC guibg=NONE ctermbg=NONE"
--
--     -- set keymaps
--     local keymap = vim.keymap -- for conciseness
--
--     keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file explorer" }) -- toggle file explorer
--     keymap.set("n", "<leader>ef", "<cmd>NvimTreeFindFile<CR>", { desc = "Toggle file explorer on current file" }) -- toggle file explorer on current file
--     keymap.set("n", "<leader>ec", "<cmd>NvimTreeCollapse<CR>", { desc = "Collapse file explorer" }) -- collapse file explorer
--     keymap.set("n", "<leader>er", "<cmd>NvimTreeRefresh<CR>", { desc = "Refresh file explorer" }) -- refresh file explorer
--     -- Autocommand for handling nvim-tree closing behavior
--     vim.api.nvim_create_autocmd({ "BufEnter", "QuitPre" }, {
--       nested = false,
--       callback = function(e)
--         local tree = require("nvim-tree.api").tree
--
--         -- Nothing to do if tree is not opened
--         if not tree.is_visible() then return end
--
--         -- How many focusable windows do we have? (excluding e.g. incline status window)
--         local winCount = 0
--         for _, winId in ipairs(vim.api.nvim_list_wins()) do
--           if vim.api.nvim_win_get_config(winId).focusable then winCount = winCount + 1 end
--         end
--
--         -- We want to quit and only one window besides tree is left
--         if e.event == "QuitPre" and winCount == 2 then vim.api.nvim_cmd({ cmd = "qall" }, {}) end
--
--         -- :bd was probably issued when only tree window is left
--         -- Behave as if tree was closed (see `:h :bd`)
--         if e.event == "BufEnter" and winCount == 1 then
--           -- Required to avoid "Vim:E444: Cannot close last window"
--           vim.defer_fn(function()
--             -- Close nvim-tree: will go to the last buffer used before closing
--             tree.toggle { find_file = true, focus = true }
--             -- Re-open nvim-tree
--             tree.toggle { find_file = true, focus = false }
--           end, 10)
--         end
--       end,
--     })
--   end,
-- }
return {}
